# -*- coding: utf-8 -*-
"""Assignment_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YIIJWLB7RYn4SWDmhiIlAWSALmdN0OC4
"""

#1
sum=0
for i in range(1,11):
  sum += i
print('Sum:', sum)

#2
n = int(input('Enter a number: '))
fact = 1
for i in range(1, n+1):
  fact *= i
print('Factorial of number: ', fact)

#3
a=0
b=1
for i in range(7):
  print(a, end=" ")
  c=a+b
  a=b
  b=c

#4
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))

if a >= b and a >= c:
    largest = a
elif b >= a and b >= c:
    largest = b
else:
    largest = c

print("Largest number is:", largest)

#5
name = input("Enter name: ")
roll_no = int(input("enter Roll. No. "))

total = 0
for i in range(1,6):
  marks= int(input("enter marks of subject: "))
  total += marks

Result= total/6
print('Percentage: ', Result)

if Result >= 90:
  print('A grade')
elif Result >= 80:
  print('B grade')
elif Result>=70:
  print('C grade')
elif Result>=60:
  print('D grade')
else:
  print('F grade')