# -*- coding: utf-8 -*-
"""assignment1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wcbOL6ZSSNpHJLbeFsisPmTCWBTGKen7
"""

#assignment1
#1. area of a rectangle
l= input('enter length of rectangle')
b= input('enter breadth of rectangle')
area= int(l)*int(b)
print('area of rectangle is',area)

#2. simple interest
P= input('enter principle amount')
R= input('enter rate of interest')
T= input('enter time')
SI= (int(P)*int(R)*int(T))/100
print('simple interest is',SI)

#3. celius to fahrenheit
C= input('enter temperature')
F= (int(C)*1.8)+ 32
print('temperature in fahrenheit', F)

#4. average of three numbers
a= input('enter first number')
b= input('enter second number')
c= input('enter third number')
avg= (int(a)+int(b)+int(c))/3
print('average of three numbers is',avg)

#5. square and cube of a number
a= input('enter a number')
square= int(a)*int(a)
cube= int(a)*int(a)*int(a)
print('square of a number is',square)
print('cube of a number is',cube)

#6. swap two numbers without third variable
a= input('enter first number')
b= input('enter second number')
a,b=b,a
print('first number after swap',a)
print('second number after swap',b)

#7. total and percentage of a student
M= input('enter marks of maths')
B= input('enter marks of biology')
C= input('enter marks of chemistry')
T= int(M)+int(B)+int(C)
P= (int(T)/300)*100
print('total marks of student is', T)
print('percentage of marks is', P)