# -*- coding: utf-8 -*-
"""assignment3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CIbuJ_FcS9Af-4tsx-_2TcEZ35mYvn8L
"""

#assignment3
#1. first 10 natural numbers
def print_first_10_natural_numbers():
    print("First 10 natural numbers:")
    for i in range(1, 11):
        print(i, end=" ")
    print()
print_first_10_natural_numbers()

#2. sum of first N natural numbers
def sum_of_n_natural_numbers(n):
    total_sum = 0
    for i in range(1, n + 1):
        total_sum += i
    return total_sum
num = 5
result = sum_of_n_natural_numbers(num)
print(f"The sum of first {num} natural numbers is: {result}")

#3. reverse a number
def reverse_number(number):
    reversed_number = 0
    while number > 0:
        digit = number % 10
        reversed_number = reversed_number * 10 + digit
        number //= 10
    return reversed_number

#4. count digits in a number
def count_digits(num):
    return len(str(abs(num)))

test_num = 987654
print(f"The number of digits in {test_num} is: {count_digits(test_num)}")

#5. check palindrome
def is_palindrome(num):
    original = num
    reverse = 0
    while num > 0:
        remainder = num % 10
        reverse = (reverse * 10) + remainder
        num = num // 10
    return original == reverse

test_num = 12321
if is_palindrome(test_num):
    print(f"{test_num} is a Palindrome number.")
else:
    print(f"{test_num} is NOT a Palindrome number.")

#6. fibonacci series
def generate_fibonacci(n):
    if n <= 0:
        return []
    elif n == 1:
        return [0]

    series = [0, 1]
    while len(series) < n:
        series.append(series[-1] + series[-2])
    return series

terms = input("Enter the number of terms for the Fibonacci series: ")
terms = int(terms)
print(f"Fibonacci series ({terms} terms): {generate_fibonacci(terms)}")

#7. calculator
def add(a, b):
    return a + b
def subtract(a, b):
    return a - b
def multiply(a, b):
    return a * b
def divide(a, b):
    if b == 0:
        return "Error! Division by zero."
    return a / b

print("Simple Calculator")
print("Select operation:\n1. Add\n2. Subtract\n3. Multiply\n4. Divide")

choice = input("Enter choice (1/2/3/4): ")

if choice in ['1', '2', '3', '4']:
    num1 = float(input("Enter first number: "))
    num2 = float(input("Enter second number: "))

    if choice == '1':
        print("Result:", add(num1, num2))
    elif choice == '2':
        print("Result:", subtract(num1, num2))
    elif choice == '3':
        print("Result:", multiply(num1, num2))
    elif choice == '4':
        print("Result:", divide(num1, num2))
else:
    print("Invalid Choice")

#8. creating text file and storing student details
with open("student_details.txt", "w") as file:
    file.write("Name: Rahul Sharma\n")
    file.write("Roll Number: 101\n")
    file.write("Course: Computer Science\n")

print("File 'student_details.txt' created and details saved successfully!")

#9. reading data from a file
try:
    with open("student_details.txt", "r") as file:
        content = file.read()
        print("--- Reading Data from File ---")
        print(content)
except FileNotFoundError:
    print("The file does not exist. Please run the previous cell first.")

#10. Handle division by zero using exception handling
def safe_division():
    try:
        numerator = float(input("Enter numerator: "))
        denominator = float(input("Enter denominator: "))

        result = numerator / denominator
        print(f"Result of division: {result}")

    except ZeroDivisionError:
        print("Exception Caught: You cannot divide a number by zero!")
    except ValueError:
        print("Exception Caught: Please enter valid numbers.")

# Run the function
safe_division()

#11. Create a Student class with name and marks
class Student:
    def __init__(self, name, marks):
        self.name = name
        self.marks = marks

    def display_details(self):
        print("\n--- Student Details ---")
        print(f"Student Name: {self.name}")
        print(f"Marks Obtained: {self.marks}")
        print(f"Total Marks: {sum(self.marks)}")

student1 = Student("Anjali Singh", [85, 92, 78])

student1.display_details()