# -*- coding: utf-8 -*-
"""assignment2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hd2gh0BBXf1BqkfR8nd7UcLxv1wN7Q_f
"""

#assignment2
#1. sum of first 10 natural numbers
s= (1,2,3,4,5,6,7,8,9,10)
a= sum(s)
print('sum of first 10 natural numbers', a)

#2. factorial of a number
a = input("Enter a number: ")
num = int(a)
if num < 0:
   print("Factorial does not exist for negative numbers.")
elif num == 0:
     print("The factorial of 0 is 1.")
else:
    factorial = 1
    for i in range(1, num + 1):
           factorial = factorial * i
           print(f"The factorial of {num} is {factorial}.")

#3. fibonacci series
n = int(input("Enter the number of terms: "))
a, b = 0, 1
print("Fibonacci Series:")
for _ in range(n):
    print(a, end=" ")
    a, b = b, a + b

#4. largest of three numbers
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
num3 = float(input("Enter the third number: "))
largest = max(num1, num2, num3)
print(f"\nThe largest number among {num1}, {num2}, and {num3} is: {largest}")

#5. student result system
num = int(input("Enter the number of students: "))
for i in range(num):
    print(f"\n Entering details for Student {i+1}")

    name = input("Enter Student Name: ")
    roll_no = input("Enter Roll Number: ")

    print("\nEnter marks obtained out of 100:")
    sub1 = float(input("Subject 1 marks: "))
    sub2 = float(input("Subject 2 marks: "))
    sub3 = float(input("Subject 3 marks: "))


    t = sub1 + sub2 + sub3
    p = (t / 300) * 100

    if p >= 90:
        grade = "A+"
    elif p >= 80:
        grade = "A"
    elif p >= 70:
        grade = "B"
    elif p >= 60:
        grade = "C"
    else:
        grade = "Fail"

    print("STUDENT REPORT")
    print(f"Name        : {name}")
    print(f"Roll No     : {roll_no}")
    print(f"Total Marks : {t:.2f} / 300")
    print(f"Percentage  : {p:.2f}%")
    print(f"Final Grade : {grade}")