# -*- coding: utf-8 -*-
"""Assignment_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yuQw7TZdKHQ26jTgeTW9KgNFDLTMN9G2
"""

#1
breadth = 4
length = 8
print("Area of rectangle : " , breadth *length)

#2
P=10000
R=5
T=3
print('simple interest:', P*R*T/100)

#3
C=int(input('Enter temperature in Celcius'))
F=(C*9/5)+32
print('Temp in Fahrenheit: ',F)

#4
a=int(input('Enter first number'))
b=int(input('Enter second number'))
c=int(input('Enter third number'))
avg= (a+b+c)/3
print('Average : ',avg)

#5
x=5
print("Square of 5: ",x**2)
print("Cube of 5: ", x**3)

#6
a = 10
b = 20

a,b = b,a

print("a =", a)
print("b =", b)

#7
#student details
input('Enter Name: ')
Subject1= int(input('Enter marks of 1st subject'))
Subject2= int(input('Enter marks of 2nd subject'))
Subject3= int(input('Enter marks of 3rd subject'))
Subject4= int(input('Enter marks of 4th subject'))
Subject5= int(input('Enter marks of 5th subject'))
#percentage
Result= ((Subject1+Subject2+Subject3+Subject4+Subject5)/500)*100
print('Percentage: ', Result)